import React from 'react'
import Header from '../components/Header'

const PageHome = () => {
    return (
        <>
            <Header />
            <main className="container mx-auto pt-6 pb-6">
                <div className='page page-home'>
                    <h1>home page</h1>
                    <h2>header 2</h2>
                    <h3>header 3</h3>
                    <h4>header four</h4>
                    <h5>header five</h5>
                    <h6>header number six</h6>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quisquam corporis accusamus esse ab illum optio? Obcaecati earum, nihil recusandae voluptatum porro, harum esse ad tempora maiores quibusdam nemo dolore! Dolorum, inventore! Possimus consequuntur, maiores harum quaerat officiis, delectus praesentium deleniti est laudantium numquam fugiat laborum repellendus voluptas nesciunt! Quisquam maxime sint nulla harum officiis inventore ullam modi voluptatibus explicabo, consequuntur ut voluptate, accusamus maiores corrupti quasi. Laborum deleniti in amet neque magni expedita quisquam molestiae omnis, asperiores quasi delectus! Libero adipisci, repellat tempore harum explicabo ipsum. Illo consectetur officia aperiam similique maxime accusantium fugiat! Iste totam accusantium atque soluta quibusdam.</p>
                </div>
            </main>
        </>

    );
}

export default PageHome;            